name: firestore_lazy_loading_totalxsoftware
description: >
  A Flutter package for implementing lazy loading and pagination with Firestore. 
  Simplifies handling large datasets by fetching data in batches as the user scrolls, 
  using a ScrollController for seamless and efficient integration.
version: 1.0.0
homepage: 'https://github.com/totalxsoftwaredevelopers/firestore_lazy_loading_totalxsoftware'

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  cloud_firestore: ^5.5.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

screenshots:
  - description: "https://www.totalx.in"
    path: assets/images/totalx.png
